#!/bin/bash
# Deploy Vectorized CPT to Google Cloud Run

PROJECT_ID="cpt-code-vectorized-dataset"
REGION="us-central1"

echo "🚀 Deploying Vectorized CPT to Google Cloud Run..."
echo "Project: $PROJECT_ID"
echo "Region: $REGION"
echo ""

# Check if gcloud is authenticated
echo "🔐 Checking Google Cloud authentication..."
if ! gcloud auth list --format="value(account)" | grep -q .; then
    echo "❌ Not authenticated with Google Cloud. Please run: gcloud auth login"
    exit 1
fi

# Set the project
echo "📋 Setting project: $PROJECT_ID"
gcloud config set project $PROJECT_ID

echo ""
echo "📦 Deploying services in optimal order..."
echo ""

# Deploy Medical Processor API
echo "1/5 📦 Deploying Medical Processor API..."
gcloud run deploy medical-processor \
    --source ./api_services/medical_processor \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8001 \
    --memory 2Gi \
    --cpu 2 \
    --timeout 300s \
    --max-instances 10 \
    --concurrency 10 \
    --quiet

if [ $? -eq 0 ]; then
    MEDICAL_PROCESSOR_URL=$(gcloud run services describe medical-processor --region=$REGION --format="value(status.url)")
    echo "✅ Medical Processor deployed: $MEDICAL_PROCESSOR_URL"
else
    echo "❌ Failed to deploy Medical Processor"
    exit 1
fi

echo ""

# Deploy CPT Search API
echo "2/5 📦 Deploying CPT Search API..."
gcloud run deploy cpt-search \
    --source ./api_services/cpt_search \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8002 \
    --memory 2Gi \
    --cpu 2 \
    --timeout 300s \
    --max-instances 10 \
    --concurrency 10 \
    --quiet

if [ $? -eq 0 ]; then
    CPT_SEARCH_URL=$(gcloud run services describe cpt-search --region=$REGION --format="value(status.url)")
    echo "✅ CPT Search deployed: $CPT_SEARCH_URL"
else
    echo "❌ Failed to deploy CPT Search"
    exit 1
fi

echo ""

# Deploy Medical Coding API
echo "3/5 📦 Deploying Medical Coding API..."
gcloud run deploy medical-coding \
    --source ./api_services/medical_coding \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8003 \
    --memory 2Gi \
    --cpu 2 \
    --timeout 300s \
    --max-instances 10 \
    --concurrency 10 \
    --quiet

if [ $? -eq 0 ]; then
    MEDICAL_CODING_URL=$(gcloud run services describe medical-coding --region=$REGION --format="value(status.url)")
    echo "✅ Medical Coding deployed: $MEDICAL_CODING_URL"
else
    echo "❌ Failed to deploy Medical Coding"
    exit 1
fi

echo ""

# Create API Gateway configuration with Cloud Run URLs
echo "4/5 📝 Updating API Gateway configuration for Cloud Run..."
cat > ./api_gateway/cloud_config.py << EOF
# Cloud Run service URLs - Auto-generated by deploy_cloud_run.sh
CLOUD_SERVICE_URLS = {
    'medical_processor': '$MEDICAL_PROCESSOR_URL',
    'cpt_search': '$CPT_SEARCH_URL', 
    'medical_coding': '$MEDICAL_CODING_URL'
}
EOF

# Deploy API Gateway
echo "4/5 📦 Deploying API Gateway..."
gcloud run deploy api-gateway \
    --source ./api_gateway \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8000 \
    --memory 2Gi \
    --cpu 2 \
    --timeout 300s \
    --max-instances 10 \
    --concurrency 20 \
    --quiet

if [ $? -eq 0 ]; then
    API_GATEWAY_URL=$(gcloud run services describe api-gateway --region=$REGION --format="value(status.url)")
    echo "✅ API Gateway deployed: $API_GATEWAY_URL"
else
    echo "❌ Failed to deploy API Gateway"
    exit 1
fi

echo ""

# Deploy Web Interface
echo "5/5 📦 Deploying Web Interface..."
# Create web interface Dockerfile
cat > ./Dockerfile.web << EOF
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt /app/
COPY api_gateway/requirements.txt /app/api_gateway_requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r api_gateway_requirements.txt

# Copy application code
COPY . /app/

# Set Python path
ENV PYTHONPATH=/app

# Expose port
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:8080/api/status || exit 1

# Run the web interface
CMD ["uvicorn", "web_server_api:app", "--host", "0.0.0.0", "--port", "8080"]
EOF

gcloud run deploy web-interface \
    --source . \
    --platform managed \
    --region $REGION \
    --allow-unauthenticated \
    --port 8080 \
    --memory 1Gi \
    --cpu 1 \
    --timeout 300s \
    --max-instances 5 \
    --concurrency 20 \
    --env-vars="API_GATEWAY_URL=$API_GATEWAY_URL" \
    --quiet

if [ $? -eq 0 ]; then
    WEB_INTERFACE_URL=$(gcloud run services describe web-interface --region=$REGION --format="value(status.url)")
    echo "✅ Web Interface deployed: $WEB_INTERFACE_URL"
else
    echo "❌ Failed to deploy Web Interface"
    exit 1
fi

echo ""
echo "🎉 ===== DEPLOYMENT COMPLETE ===== 🎉"
echo ""
echo "🌐 Your Vectorized CPT services are now live:"
echo ""
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│                    SERVICE URLS                             │"
echo "├─────────────────────────────────────────────────────────────┤"
echo "│ 🖥️  Web Interface:    $WEB_INTERFACE_URL"
echo "│ 🚪 API Gateway:       $API_GATEWAY_URL"  
echo "│ 🤖 Medical Processor: $MEDICAL_PROCESSOR_URL"
echo "│ 🔍 CPT Search:        $CPT_SEARCH_URL"
echo "│ 🏥 Medical Coding:    $MEDICAL_CODING_URL"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "🔑 NEXT STEPS:"
echo "1. Visit your Web Interface: $WEB_INTERFACE_URL"
echo "2. Configure an API key through the web interface"  
echo "3. Test the complete medical coding workflow"
echo "4. Use the health dashboard to monitor services"
echo ""
echo "📚 API Documentation:"
echo "   Gateway Docs: $API_GATEWAY_URL/docs"
echo "   Health Check: $API_GATEWAY_URL/health"
echo ""
echo "💡 The system is ready for production use!"
echo "   - All services have HTTPS by default"
echo "   - Auto-scaling based on demand"
echo "   - API key authentication enabled"
echo "   - Rate limiting: 1000 requests/hour per key"
echo ""

# Save URLs to a file for reference
cat > ./cloud_urls.txt << EOF
Vectorized CPT - Cloud Run Deployment URLs
==========================================

Web Interface: $WEB_INTERFACE_URL
API Gateway: $API_GATEWAY_URL
Medical Processor: $MEDICAL_PROCESSOR_URL  
CPT Search: $CPT_SEARCH_URL
Medical Coding: $MEDICAL_CODING_URL

Deployed on: $(date)
Project: $PROJECT_ID
Region: $REGION
EOF

echo "💾 Service URLs saved to: cloud_urls.txt"
echo ""
echo "🚀 Deployment complete! Your system is live and ready to use."